# Site settings
title: "Rising Dawns: Adventure"
description: "City-building and Empire-expanding game. Collect resources, train soldiers, build buildings, research, or really, do whatever you want."
